DROP TABLE IF EXISTS pilot;
CREATE TABLE pilot (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR (50) NOT NULL,
  license_number VARCHAR (50) NOT NULL UNIQUE,
  fly_hour INT NOT NULL
);

DROP TABLE IF EXISTS flight;
CREATE TABLE flight (
  id BIGINT PRIMARY KEY AUTO_INCREMENT;
  flight_number VARCHAR (50) NOT NULL;
  origin VARCHAR (50) NOT NULL,
  destination VARCHAR (50) NOT NULL,
  time DATE DEFAULT NULL,

)
